# Generated by Django 5.2.1 on 2025-05-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputused',
            options={'verbose_name': 'Input Used', 'verbose_name_plural': 'Inputs Used'},
        ),
    ]
