# Generated by Django 5.2.1 on 2025-06-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the inventory item, e.g., 'Urea Fertilizer'", max_length=100)),
                ('category', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('equipment', 'Equipment'), ('fuel', 'Fuel'), ('other', 'Other')], default='other', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Current quantity in stock', max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('liters', 'Liters'), ('ml', 'Milliliters'), ('units', 'Units'), ('sacks', 'Sacks')], default='units', help_text='Measurement unit, e.g., kg, liters, units', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
